# Generated by Django 4.1.1 on 2022-09-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MshopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilename', models.CharField(max_length=220)),
                ('mobileram', models.CharField(max_length=220)),
                ('mobilerom', models.CharField(max_length=100)),
                ('mobilecolour', models.CharField(max_length=100)),
                ('mobilebattery', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
